# Use the official Python 3.7 image as the base image
FROM python:3.7

# Set environment variables
ENV TF_VERSION=2.15.0

# Install TensorFlow
RUN pip install tensorflow==$TF_VERSION

# Install any other dependencies you need
# For example:
# RUN pip install numpy pandas matplotlib

# Set the default shell to bash
ENV SHELL /bin/bash
